name: raster_tutorial
channels:
  - conda-forge
dependencies:
  - python=3.13
  - jupyterlab=4.4.7
  - pystac-client=0.9.0
  - planetary-computer=1.0.0
  - leafmap=0.54.0
  - matplotlib
  - dask=2025.10.0
  - dask-labextension
  - distributed=2025.10.0
  - rioxarray=0.20.0